name: Run Load Test with HTML Report

on:
  workflow_dispatch:

jobs:
  load_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install JMeter
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jre
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xvzf apache-jmeter-5.5.tgz
        export JMETER_HOME=$PWD/apache-jmeter-5.5
        export PATH=$JMETER_HOME/bin:$PATH

    - name: Run Load Test
      run: |
        mkdir -p results/load
        jmeter -n -t POC_PerfTestSuit_LoadTest.jmx -l results/load/results_load.jtl -e -o results/load/html_report

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: load-html-report
        path: results/load/html_report
