name: Run Spike Test with HTML Report

on:
  workflow_dispatch:

jobs:
  spike_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install JMeter
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jre
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        echo "JMETER_HOME=$PWD/apache-jmeter-5.6.3" >> $GITHUB_ENV
        echo "PATH=$PWD/apache-jmeter-5.6.3/bin:$PATH" >> $GITHUB_ENV

    - name: Run Spike Test
      run: |
        mkdir -p results/spike/html_report
        jmeter -n -t tests/POC_PerfTestSuit_SpikeTest.jmx -l results/spike/results_spike.jtl -e -o results/spike/html_report

    - name: Upload Spike HTML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spike-html-report
        path: results/spike/html_report

    - name: Commit and Push HTML Report to GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git fetch
        git checkout results || git checkout -b results
        mkdir -p reports/spike
        cp -r results/spike/html_report/* reports/spike/
        git add reports/spike
        git commit -m "Add Spike Test HTML report - $(date)"
        git push origin results
