name: Run Stress Test with HTML Report

on:
  workflow_dispatch:

jobs:
  stress_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install JMeter
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jre
        wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xvzf apache-jmeter-5.5.tgz
        export JMETER_HOME=$PWD/apache-jmeter-5.5
        export PATH=$JMETER_HOME/bin:$PATH

    - name: Run Stress Test
      run: |
        mkdir -p results/stress
        jmeter -n -t POC_PerfTestSuit_StressTest.jmx -l results/stress/results_stress.jtl -e -o results/stress/html_report

    - name: Upload Stress HTML Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: stress-html-report
        path: results/stress/html_report

    - name: Commit and Push HTML Report to GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git fetch
        git checkout results || git checkout -b results
        mkdir -p reports/stress
        cp -r results/stress/html_report/* reports/stress/
        git add reports/stress
        git commit -m "Add Stress Test HTML report - $(date)"
        git push origin results
